# Generated by Django 2.1.3 on 2020-02-02 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0005_auto_20200202_0436'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.SmallIntegerField(choices=[(100, 'Pending'), (101, 'Polling'), (102, 'Pending'), (110, 'Ignored'), (120, 'Warning'), (130, 'Accepted'), (140, 'Rejected')])),
                ('pub_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
                'db_table': 'users_violation',
                'ordering': ['-pub_date'],
                'permissions': (('can_vote_violation', 'Can vote.'), ('can_report_violation', 'Can report.'), ('can_comment_violation', 'Can comment.'), ('can_resolve_violation', 'Can resolve.')),
            },
        ),
        migrations.CreateModel(
            name='ViolationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, '----'), (101, 'Open Poll'), (102, 'Close Poll'), (110, 'Ignore'), (120, 'Warn'), (130, 'Accept'), (140, 'Reject')], default=0)),
                ('comment', models.CharField(blank=True, max_length=750)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Violation Feedback',
                'verbose_name_plural': 'Violation Feedback',
                'db_table': 'users_violation_feedback',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ViolationVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, '----'), (110, 'Ignore'), (120, 'Warn'), (130, 'Accept'), (140, 'Reject')], default=0)),
            ],
            options={
                'verbose_name': 'Violation Vote',
                'verbose_name_plural': 'Violation Votes',
                'db_table': 'users_violation_vote',
            },
        ),
        migrations.RemoveField(
            model_name='feedbackcontribution',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedbackcontribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='theory_node',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='utilized',
            field=models.ManyToManyField(blank=True, related_name='users', to='theories.TheoryNode'),
        ),
        migrations.DeleteModel(
            name='FeedbackContribution',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
        migrations.AddField(
            model_name='violationvote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violationvote',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.Violation'),
        ),
        migrations.AddField(
            model_name='violationfeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violationfeedback',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='users.Violation'),
        ),
        migrations.AddField(
            model_name='violation',
            name='offender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL),
        ),
    ]
