# Generated by Django 2.2.10 on 2020-03-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200202_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='violationfeedback',
            name='violation',
        ),
        migrations.RemoveField(
            model_name='violationvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='violationvote',
            name='violation',
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
        migrations.DeleteModel(
            name='ViolationFeedback',
        ),
        migrations.DeleteModel(
            name='ViolationVote',
        ),
    ]
