# Generated by Django 2.2.10 on 2020-03-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0003_auto_20200309_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL)),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.SmallIntegerField(choices=[(100, 'Pending'), (101, 'Polling'), (102, 'Pending'), (110, 'Ignored'), (120, 'Warning'), (130, 'Strike')], default=100)),
                ('read', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
                'db_table': 'users_violation',
                'ordering': ['-pub_date'],
                'permissions': (('can_vote_violation', 'Can vote.'), ('can_report_violation', 'Can report.'), ('can_comment_violation', 'Can comment.'), ('can_resolve_violation', 'Can resolve.')),
            },
        ),
        migrations.CreateModel(
            name='ViolationVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(0, '----'), (110, 'Ignore'), (120, 'Warn'), (130, 'Strike')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_votes', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.Violation')),
            ],
            options={
                'verbose_name': 'Violation Vote',
                'verbose_name_plural': 'Violation Votes',
                'db_table': 'users_violation_vote',
            },
        ),
        migrations.CreateModel(
            name='ViolationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=750)),
                ('pub_date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_feedback', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='users.Violation')),
            ],
            options={
                'verbose_name': 'Violation Feedback',
                'verbose_name_plural': 'Violation Feedback',
                'db_table': 'users_violation_feedback',
                'ordering': ['pub_date'],
            },
        ),
    ]
