version = 1

test_patterns = ["/*/tests/*.py"]

exclude_patterns = [
    "migrations/**",
    "/core/static/vendor/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_check = 100

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "browser",
    "jquery"
  ]
  style_guide = "google"
  dialect = "typescript"
