# Generated by Django 2.2.10 on 2020-04-17 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dependencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='parents', to='theories.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='flat_dependencies',
            field=models.ManyToManyField(blank=True, related_name='parent_flat_theories', to='theories.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_dependencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='theories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='theories.Content'),
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('content', 'stats_type')},
        ),
        migrations.AlterUniqueTogether(
            name='opiniondependency',
            unique_together={('content', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('content', 'user')},
        ),
    ]
