# Generated by Django 2.1.3 on 2019-02-21 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='theorynode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theorynode',
            name='flat_nodes',
            field=models.ManyToManyField(blank=True, related_name='parent_flat_nodes', to='theories.TheoryNode'),
        ),
        migrations.AddField(
            model_name='theorynode',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theorynode',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='parent_nodes', to='theories.TheoryNode'),
        ),
        migrations.AddField(
            model_name='statsnode',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='theories.Stats'),
        ),
        migrations.AddField(
            model_name='statsnode',
            name='theory_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_nodes', to='theories.TheoryNode'),
        ),
        migrations.AddField(
            model_name='statsflatnode',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_nodes', to='theories.Stats'),
        ),
        migrations.AddField(
            model_name='statsflatnode',
            name='theory_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_flat_nodes', to='theories.TheoryNode'),
        ),
        migrations.AddField(
            model_name='stats',
            name='opinions',
            field=models.ManyToManyField(blank=True, related_name='stats', to='theories.Opinion'),
        ),
        migrations.AddField(
            model_name='stats',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='theories.TheoryNode'),
        ),
        migrations.AddField(
            model_name='opinionnode',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='theories.Opinion'),
        ),
        migrations.AddField(
            model_name='opinionnode',
            name='theory_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_nodes', to='theories.TheoryNode'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='theories.TheoryNode'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_theories',
            field=models.ManyToManyField(blank=True, related_name='old_categories', to='theories.TheoryNode'),
        ),
        migrations.AlterUniqueTogether(
            name='statsnode',
            unique_together={('parent', 'theory_node')},
        ),
        migrations.AlterUniqueTogether(
            name='statsflatnode',
            unique_together={('parent', 'theory_node')},
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('theory', 'stats_type')},
        ),
        migrations.AlterUniqueTogether(
            name='opinionnode',
            unique_together={('parent', 'theory_node')},
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('theory', 'user')},
        ),
    ]
