# Generated by Django 2.2.10 on 2020-12-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0002_auto_20200417_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title01',
            field=models.CharField(max_length=255),
        ),
    ]
