# Generated by Django 2.1.3 on 2019-03-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0002_auto_20190221_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
