# Generated by Django 2.1.3 on 2019-03-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0003_opinion_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorynode',
            name='utilization',
            field=models.IntegerField(default=0),
        ),
    ]
