# Generated by Django 2.2.10 on 2020-03-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0005_auto_20200202_0436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted_theories',
        ),
    ]
