# Generated by Django 2.2.10 on 2020-03-21 02:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_violation_violationfeedback_violationvote'),
        ('theories', '0006_auto_20200309_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheoryNode',
            new_name='Content',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-rank'], 'permissions': (('swap_title', 'Can swap true/false title.'), ('change_title', 'Can change title.'), ('change_details', 'Can change details.'), ('delete_reversion', 'Can delete revision.'), ('merge_content', 'Can merge nodes.'), ('backup_content', 'Can create backup.'), ('remove_content', 'Can remove content.'), ('restore_content', 'Can restore/revert from revision.'), ('convert_content', 'Can convert theory <=> evidence.')), 'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='theory',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='opinionnode',
            old_name='theory_node',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='theory',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='statsflatnode',
            old_name='theory_node',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='statsnode',
            old_name='theory_node',
            new_name='content',
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('content', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='opinionnode',
            unique_together={('content', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('content', 'stats_type')},
        ),
        migrations.AlterUniqueTogether(
            name='statsflatnode',
            unique_together={('content', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='statsnode',
            unique_together={('content', 'parent')},
        ),
        migrations.AlterModelTable(
            name='content',
            table='theories_content',
        ),
    ]
